<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cart;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
    /**
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em,
            new Mapping\ClassMetadata(Cart::class));
    }

    /**
     * @param $cart
     * @return int
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(Cart $cart)
    {
        $this->_em->persist($cart);
        $this->_em->flush();
        return $cart->getId();
    }


    public function removeTyreFromCart($tyreId,$cartId){
        $query=$this->createQueryBuilder('c')
            ->select('c')
            ->from('AppBundle:Cart','cart')
            ->leftJoin('c.tyres','tyres', 'WITH','c.id = :cartId')
            ->setParameter('cartId',$cartId)
            ->where('tyres.id = :tyreId')
            ->setParameter('tyreId',$tyreId)
            ->getQuery()
            ->getResult();
        dump($query);
        exit();

    }

    public function findCartWithPurchasesDetails($userId)
    {
        $query =$this->createQueryBuilder('cart')
            ->select('cart,purchaseDetails')
            ->from('AppBundle:Cart', 'c')
            ->where('cart.user = :userId')
            ->setParameter('userId',$userId)
            ->leftJoin('cart.purchase_details','purchaseDetails')
            ->getQuery();
        return $query->getResult();

    }

}
