<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cart;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
    /**
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em,
            new Mapping\ClassMetadata(Cart::class));
    }

    /**
     * @param $cart
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(Cart $cart)
    {
        $this->_em->persist($cart);
        $this->_em->flush();
    }

//    /**
//     * @param Cart $cart
//     * @throws \Doctrine\ORM\OptimisticLockException
//     */
//    public function remove(Cart $cart){
//        $this->_em->remove($cart);
//        $this->_em->flush();
//    }

    public function removeTyreFromCart($tyreId,$cartId){
//        $query=$this->createQueryBuilder('c')
//            ->select('c.tyres')
//            ->addSelect('tyres.carts')
//            ->from('AppBundle:Cart','cart')
//            ->innerJoin('c.tyres', 'tyres')
//            ->where('c.id = :cartId')
//            ->setParameter('cartId',$cartId)
//            ->getQuery();

    }

}
