<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Comment;
use AppBundle\Entity\Tyre;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * UserRepository constructor.
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em,
            new Mapping\ClassMetadata(Comment::class));
    }

    /**
     * @param Comment $comment
     */
    public function save(Comment $comment)
    {
        $this->_em->persist($comment);
        $this->_em->flush();
    }
}
