<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Promotion;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
    /**
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em,
            new Mapping\ClassMetadata(Promotion::class));
    }

    public function save(Promotion $promotion){
        $this->_em->persist($promotion);
        $this->_em->flush();
    }
}
