<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Purchase;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{
    /**
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em,
            new Mapping\ClassMetadata(Purchase::class));
    }

    /**
     * @param $purchase
     */
    public function save($purchase){
        $this->_em->persist($purchase);
        $this->_em->flush();
    }

    /**
     * @return array
     */
    public function findAllPurchases()
    {
        $query =$this->createQueryBuilder('purchase')
            ->select('purchase, user, purchasesDetails')
            ->from('AppBundle:Purchase', 'p')
            ->leftJoin('purchase.userId','user')
            ->leftJoin('purchase.purchasesDetails','purchasesDetails')
            ->getQuery();
        return $query->getResult();
    }
}
