<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Purchase;
use AppBundle\Entity\PurchasesDetails;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends EntityRepository
{
    /**
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em,
            new Mapping\ClassMetadata(Purchase::class));
    }

    /**
     * @param $purchase
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save($purchase){
        $this->_em->persist($purchase);
        $this->_em->flush();
    }

}
