<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tyre;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * TyreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TyreRepository extends EntityRepository
{
    /**
     * UserRepository constructor.
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em,
            new Mapping\ClassMetadata(Tyre::class));
    }

    /**
     * @param Tyre $tyre
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function save(Tyre $tyre){
        $this->_em->persist($tyre);
        $this->_em->flush();
    }

    /**
     * @param Tyre $tyre
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function remove(Tyre $tyre){
        $this->_em->remove($tyre);
        $this->_em->flush();
    }
}
